# Generated by Django 3.0.7 on 2020-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favflamz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Phone_number', models.BigIntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
