# Generated by Django 3.0.7 on 2020-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favflamz_app', '0002_auto_20200626_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='Phone_number',
            field=models.IntegerField(max_length=200),
        ),
    ]
