# Generated by Django 3.0.7 on 2020-07-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favflamz_app', '0004_auto_20200626_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='First_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='Last_name',
            new_name='username',
        ),
    ]
